### ISSUE TITLE
[Enhancement] "Safe"

### ISSUE THREAD

**Issue by SammCheese** [D-Brox/holy-notes#12]
Id Suggest an Extra Button in the Modal that switches to a second Notebook Tab, aswell as a Command that moves notes to that second Notebook Tab.

Y'know, for the more *spicy* Messages/Pictures

**Comment by D-Brox** [comment]
Or multiple notebooks to store by category

**Comment by D-Brox** [comment]
Would need some reworking on the Modal and on the noteHandler, so I guess this will be have for 1.3
