### ISSUE TITLE
Crashing Issues

### ISSUE THREAD

**Issue by divine-ray** [D-Brox/holy-notes#14]
Everytime I try to open, edit, or delete something in the notebook, i get this error:
![grafik](https://user-images.githubusercontent.com/29178731/109329362-c2788480-785a-11eb-9293-f6502c61ba7c.png)
![grafik](https://user-images.githubusercontent.com/29178731/109329803-52b6c980-785b-11eb-9dfb-314f5e4dde26.png)

**Comment by D-Brox** [comment]
Fixed in 1.2.6
