### ISSUE TITLE
 messages dont update when no longer accessable.

### ISSUE THREAD

**Issue by Captain8771** [D-Brox/holy-notes#22]
# how to reproduce:

Create a server, and note a message. now delete that server and check your notes.

## expected:

Note gone

## actual behavior:

note still there

**Comment by MulverineX** [comment]
Works as intended. Just as a screenshot of a message you've saved will always be there.

**Comment by D-Brox** [comment]
Personal Pins and Ghost Pings are the only instances of message logging allowed by the powercord  guidelines.
First one because it requires user interaction, and acts like a screenshot
Second one because because ghost pings are messages sent specifically to you
